import {Food, FoodType, Nutrition} from "./types";

export const recommendedIntake: Nutrition = {
  a: 0.7,
  c: 75,
  iron: 18,
  k: 0.09,
  fiber: 30000,
  calcium: 1000,
  omega3: 4000,
  omega6: 12000,
  zinc: 8,
  d: 0.015,
  iodine: 0.15,
  selenium: 0.055,
}

export const foodCollection: Food[] = [
  {
    name: "plum",
    description: "2 plums",
    type: FoodType.FRUIT,
    gramsInPortion: 156,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "kiwi",
    description: "2 kiwi fruits",
    type: FoodType.FRUIT,
    gramsInPortion: 152,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "apricot",
    description: "3 apricots",
    type: FoodType.FRUIT,
    gramsInPortion: 150,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "strawberry",
    description: "7 strawberries",
    type: FoodType.FRUIT,
    gramsInPortion: 84,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "cherry",
    description: "14 cherries",
    type: FoodType.FRUIT,
    gramsInPortion: 115,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "apple",
    description: "1 apple",
    type: FoodType.FRUIT,
    gramsInPortion: 85,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "banana",
    description: "1 banana",
    type: FoodType.FRUIT,
    gramsInPortion: 118,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "pear",
    description: "1 pear",
    type: FoodType.FRUIT,
    gramsInPortion: 178,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "orange",
    description: "1 orange",
    type: FoodType.FRUIT,
    gramsInPortion: 154,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "grapefruit",
    description: "half a grapefruit",
    type: FoodType.FRUIT,
    gramsInPortion: 123,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "melon",
    description: "1 slice of melon (5cm)",
    type: FoodType.FRUIT,
    gramsInPortion: 70,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "pineapple",
    description: "1 large slice of pineapple",
    type: FoodType.FRUIT,
    gramsInPortion: 102,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "raisins",
    description: "1 tablespoon of raisins",
    type: FoodType.FRUIT,
    gramsInPortion: 10,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "fig",
    description: "2 dried figs",
    type: FoodType.FRUIT,
    gramsInPortion: 28,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "prune",
    description: "3 prunes",
    type: FoodType.FRUIT,
    gramsInPortion: 28,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0,
      k: 0,
      fiber: 0,
      calcium: 0,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "broccoli",
    description: "2 broccoli spears",
    type: FoodType.VEGETABLE,
    gramsInPortion: 62,
    nutritionInPortion: {
      a: 0.0868,
      c: 58.28,
      iron: 0.496,
      k: 0,
      fiber: 0,
      calcium: 35.96,
      omega3: 0,
      omega6: 0,
      zinc: 0.31,
      d: 0,
      iodine: 0.0093,
      selenium: 0,
    }
  },
  {
    name: "kale",
    description: "4 tablespoons of cooked kale",
    type: FoodType.VEGETABLE,
    gramsInPortion: 60,
    nutritionInPortion: {
      a: 0.516,
      c: 63,
      iron: 1.14,
      k: 0,
      fiber: 0,
      calcium: 127.2,
      omega3: 0,
      omega6: 0,
      zinc: 0.18,
      d: 0,
      iodine: 0.006,
      selenium: 0,
    }
  },
  {
    name: "spinach",
    description: "4 tablespoons of cooked spinach",
    type: FoodType.VEGETABLE,
    gramsInPortion: 8,
    nutritionInPortion: {
      a: 0.0624,
      c: 3.04,
      iron: 0.312,
      k: 0,
      fiber: 0,
      calcium: 9.52,
      omega3: 0,
      omega6: 0,
      zinc: 0.048,
      d: 0,
      iodine: 0.00096,
      selenium: 0,
    }
  },
  {
    name: "carrot",
    description: "3 tablespoons of cooked carrots",
    type: FoodType.VEGETABLE,
    gramsInPortion: 17,
    nutritionInPortion: {
      a: 0.102,
      c: 1.19,
      iron: 0.068,
      k: 0,
      fiber: 0,
      calcium: 4.08,
      omega3: 0,
      omega6: 0,
      zinc: 0.034,
      d: 0.000136,
      iodine: 0.00017,
      selenium: 0,
    }
  },
  {
    name: "pea",
    description: "3 tablespoons of cooked peas",
    type: FoodType.VEGETABLE,
    gramsInPortion: 25,
    nutritionInPortion: {
      a: 0.05,
      c: 6.5,
      iron: 0.475,
      k: 0,
      fiber: 0,
      calcium: 5.5,
      omega3: 0,
      omega6: 0,
      zinc: 0.2,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "corn",
    description: "3 tablespoons of sweetcorn",
    type: FoodType.VEGETABLE,
    gramsInPortion: 28,
    nutritionInPortion: {
      a: 0.0028,
      c: 3.36,
      iron: 0.112,
      k: 0,
      fiber: 0,
      calcium: 0.84,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0.00084,
      selenium: 0,
    }
  },
  {
    name: "cauliflower",
    description: "8 cauliflower florets",
    type: FoodType.VEGETABLE,
    gramsInPortion: 104,
    nutritionInPortion: {
      a: 0,
      c: 66.56,
      iron: 0.52,
      k: 0,
      fiber: 0,
      calcium: 22.88,
      omega3: 0,
      omega6: 0,
      zinc: 0.312,
      d: 0,
      iodine: 0.00104,
      selenium: 0,
    }
  },
  {
    name: "tomato",
    description: "1 medium tomato",
    type: FoodType.VEGETABLE,
    gramsInPortion: 123,
    nutritionInPortion: {
      a: 0.0492,
      c: 23.37,
      iron: 0.369,
      k: 0,
      fiber: 0,
      calcium: 11.07,
      omega3: 0,
      omega6: 0,
      zinc: 0.123,
      d: 0,
      iodine: 0.00123,
      selenium: 0,
    }
  },
  {
    name: "cherryTomato",
    description: "7 cherry tomatoes",
    type: FoodType.VEGETABLE,
    gramsInPortion: 196,
    nutritionInPortion: {
      a: 0.1568,
      c: 49,
      iron: 0.98,
      k: 0,
      fiber: 0,
      calcium: 27.44,
      omega3: 0,
      omega6: 0,
      zinc: 0.392,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "cucumber",
    description: "5cm piece of cucumber",
    type: FoodType.VEGETABLE,
    gramsInPortion: 150,
    nutritionInPortion: {
      a: 0.105,
      c: 12,
      iron: 0.75,
      k: 0,
      fiber: 0,
      calcium: 22.5,
      omega3: 0,
      omega6: 0,
      zinc: 0.3,
      d: 0,
      iodine: 0.0045,
      selenium: 0,
    }
  },
  {
    name: "bakedBeans",
    description: "3 tablespoon of baked beans",
    type: FoodType.BEAN,
    gramsInPortion: 45,
    nutritionInPortion: {
      a: 0.009,
      c: 2.7,
      iron: 0.585,
      k: 0,
      fiber: 0,
      calcium: 11.25,
      omega3: 0,
      omega6: 0,
      zinc: 0,
      d: 0,
      iodine: 0,
      selenium: 0,
    }
  },
  {
    name: "kidneyBeans",
    description: "3 tablespoon of kidney beans",
    type: FoodType.BEAN,
    gramsInPortion: 33,
    nutritionInPortion: {
      a: 0,
      c: 0,
      iron: 0.429,
      k: 0,
      fiber: 0,
      calcium: 9.9,
      omega3: 0,
      omega6: 0,
      zinc: 0.264,
      d: 0,
      iodine: 0.0009,
      selenium: 0,
    }
  },
  {
    name: "chickpeas",
    description: "3 tablespoon of chickpeas",
    type: FoodType.BEAN,
    gramsInPortion: 30,
    nutritionInPortion: {
      a: 0.03,
      c: 0.3,
      iron: 0.81,
      k: 0,
      fiber: 0,
      calcium: 14.7,
      omega3: 0,
      omega6: 0,
      zinc: 0.42,
      d: 0,
      iodine: 0.0027,
      selenium: 0,
    }
  },
];
